@startmindmap

+ 技術習得
++ モダンWebアプリ
+++ 技術要素
++++ フロントエンド
+++++ React
+++++ Redux
++++++ **re-duck`sパターン**
++++++ redux-saga
+++++ Atomic Design
++++ バックエンド
+++++ サーバーフレームワーク
++++++ express
+++++ DB/ミドルウェア
++++++ postgresql
++++++ GraphQL
+++++++ apollo
+++ アプリの目的
++++ 開発現場での課題の解消
+++++ **レビュー品質の均一化/向上**
++++++ レビュー記録
+++++++ 記録のバージョン管理
+++++++ レビュー参加者を記録
+++++++ 指摘箇所と指摘内容を管理
++++++ レビューに対しての評価
+++++++ チェックリストにフィードバック
++++++ 観点をチェックリスト化
+++++++ チェックリストの更新
++++++ レビュー工程をWebアプリで完結させる
+++++++ レビュー対象のビューア
+++++++ 指摘箇所のマーキング機能
++++++ 指摘の検索
+++++ 設計ドキュメントの不足
+++++ テスト項目書の修正に時間がかかる

@endmaindmap