version: '3.1'

services:

    mongo:
        build:
            context: . 
            dockerfile: docker/mongo/Dockerfile
        restart: always
        ports:
            - 27017
        volumes:
            - mongo_db:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME
            - ME_CONFIG_MONGODB_ADMINPASSWORD
        depends_on:
            - mongo

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:8080
        links:
            - mongo
        depends_on:
            - mongo

volumes:
    mongo_db: