@startuml

' ##クラス定義 - view##
package views {
    package component {
        class loginForm {
            Status status

            void updateId(String)
            void updatePassword(String)
            void login()
        }

        class userListView {
            User[] userList
            Filter condition

            void search()
            void delete(String)
        }

        class userEditForm {
            User userInfo
            Mode mode

            void editUser()
        }

        class reviewRequestForm {
            ReviewInfo reviewInfo

            void createReviewRequest()
        }

        class reviewListView {
            ReviewInfo[] reviewInfoList

            void showDetail(String)
            void delete(String)
        }

        class reviewEditForm {
            ReviewInfo reviewInfo
            Mode mode

            void editReview()
        }

        class projectListView {
            ProjectInfo[] projectsInfoList

            void showProject(String)
            void editProject(String)
            void createProject()
            void deleteProject(String)
        }

        class projectEditForm {
            ProjectInfo ProjectInfo
            Mode mode

            void projectEdit()
        }

        class checkListView {
            CheckList[] checkLists

            void show(String)
            void delete(String)
        }

        class checkListEditForm {
            CheckList checkList
            Mode mode

            void editCheckList()
        }

        class menubar {
            String content
            Role role
            ConsoleContents consoleContents

            void showUserList()
            void createReviewRequest()
            void showReviewList()
            void showProjectList()
            void createCheckList()
            void showCheckList()
            void Logout()
        }

        class consoleContents {
            userListPage userListPage
            userEditPage userEditPage
            reviewRequestPage reviewRequestPage
            reviewListPage reviewListPage
            reviewEditPage reviewEditPage
            projectListPage projectListPage
            projectEditPage projectEditPage
            checkListPage checkListPage
            checkListEditPage checkListEditPage
        }

        ' 共通化した部品
        package molecules {
            class listViewTable {
                Column[] columns
                Object[] rows
                String linkKey
                
                void handleAction()
            }
        }
    }

    package containers {
        class loginPage {
            loginFormState state
            loginForm component

            void login()
        }

        class userListPage {
            userListViewState state
            userListView component

            void search()
            void delete(String)
        }

        class userEditPage {
            userEditFormState state
            userEditForm component

            void editUser()
        }

        class reviewRequestPage {
            reviewRequestFormState state
            reviewRequestForm component

            void createReviewRequest()
        }

        class reviewListPage {
            reviewListViewState state
            reviewListView component

            void showDetail(String)
            void delete(String)
        }

        class reviewEditPage {
            reviewEditFormState state
            reviewEditForm component

            void editReview()
        }

        class projectListPage {
            projectListViewState state
            projectListView component

            void showProject(String)
            void editProject(String)
            void createProject()
            void deleteProject(String)
        }

        class projectEditPage {
            projectEditFormState state
            projectEditForm component

            void projectEdit()
        }

        class checkListPage {
            checkListViewState state
            checkListView component

            void show(String)
            void delete(String)
        }

        class checkListEditPage {
            checkListEditFormState state
            checkListEditForm component

            void editCheckList()
        }

        class consolePage {
            menubarState state
            menubar component

            void showUserList()
            void createReviewRequest()
            void showReviewList()
            void showProjectList()
            void createCheckList()
            void showCheckList()
            void Logout()
        }
    }
}

' ##クラス定義 - duck's##
package state {
    package ducks {
        class loginFormState {
            LoginInfo loginInfo
            Status status
        }

        class userListViewState {
            User[] userList
            Fliter fliter
        }

        class userEditFormState {
            User userInfo
            Mode mode
        }

        class reviewRequestFormState {
            ReviewInfo reviewInfo
        }

        class reviewListViewState {
            ReviewInfo[] reviewInfoList
        }

        class reviewEditFormState {
            ReviewInfo reviewInfo
            Mode mode
        }

        class projectListViewState {
            ProjectInfo[] projectInfoList
        }

        class projectEditFormState {
            ProjectInfo projectInfo
        }

        class checkListViewState {
            CheckList[] checkLists
        }

        class checkListEditFormState {
            CheckList checkList
            Mode mode
        }

        class menubarState {
            String content
            SystemRole role
        }
    }
}

package types {
    enum LoginStatus {
        "INIT"
        "LOGGINGIN"
        "FAILED"
        "SUCCESS"
    }

    class LoginInfo {
        String id
        String password
    }

    enum SystemRole {
        "ADMINISTRATOR"
        "USER"
    }

    enum ProjectRole {
        "MANAGER"
        "MEMBER"
    }

    class User {
        String id
        String eMailAddress
        String firstName
        String lastName
        SystemRole role
    }

    class Filter {
        String[] ids
        String title
        String[] tags
    }

    enum Mode {
        "CREATE"
        "UPDATE"
        "VIEW"
    }

    enum Scope {
        "PUBLIC"
        "PRIVATE"
        "PROJECT"
    }

    enum ReviewStatus {
        "NEW"
        "REVIEWING"
        "MODEFIED"
        "FINISHED"
    }

    enum ReviewMemberType {
        "REVIEWEE"
        "REVIEWER"
        "PARTICIPANT"
    }

    class PointOut {
        String id
        String title
        String targetPosition
        String detail
        Boolean expand
    }

    class ReviewMember {
        User member
        ReviewMemberType memberType
    }

    class ReviewInfo {
        String id
        String title
        String documentPath
        String[] tags
        String[] checkListIds
        PointOut[] pointOutList
        ReviewMember[] reviewMembers
        ReviewStatus status
        Scope scope
    }

    class ProjectMember {
        User user
        ProjectRole role
    }

    class ProjectInfo {
        String id
        ProjectMember[] members
        String detail
        ReviewInfo[] reviewList
        Scope scope
    }

    class CheckItem {
        String id
        String title
        String detail
        Boolean performed
    }

    class CheckList {
        String id
        String title
        CheckItem[] items
    }

    class Column {
        String id
        String name
    }
}

' ##クラス相互関係##
' ##型定義クラス相互関係##
CheckList "1" o-- "1" CheckItem

User "1" *-- "1" SystemRole

ProjectMember "1" *-- "1" User
ProjectMember "1" *-- "1" ProjectRole

ReviewInfo "1" o-- "0..*" PointOut
ReviewInfo "1" o-- "1..*" User
ReviewInfo "1" o-- "1" ReviewStatus
ReviewInfo "1" o-- "1" Scope

ProjectInfo "1" ..> "1" Scope

ReviewMember "1" *-- "1" User
ReviewMember "1" *-- "1" ReviewMemberType

' ##型 - React State 相関関係##
loginFormState "1" *-- "1" LoginInfo
loginFormState "1" *-- "1" LoginStatus

userListViewState "1" *-- "0..*" User
userListViewState "1" *-- "1" Filter

userEditFormState "1" *-- "1" User
userEditFormState "1" *-- "1" Mode

reviewRequestFormState "1" o-- "1" ReviewInfo

reviewListViewState "1" o-- "0..*" ReviewInfo

reviewEditFormState "1" *-- "1" ReviewInfo
reviewEditFormState "1" *-- "1" Mode

projectListViewState "1" o-- "0..*" ProjectInfo

projectEditFormState "1" o-- "1" ProjectInfo

checkListViewState "1" o-- "0..*" CheckList

checkListEditFormState "1" *-- "1" CheckList
checkListEditFormState "1" *-- "1" Mode

menubarState "1" *-- "1" SystemRole

listViewTable "1" *-- "0..*" Column

' ##コンポーネント - 共通部品相関関係 ##
listViewTable ..> userListView
listViewTable ..> reviewListView
listViewTable ..> projectListView
listViewTable ..> checkListView

' ##コンテナ - コンポーネント相関関係##
loginForm ..> loginPage
userListView ..> userListPage
userEditForm ..> userEditPage
reviewRequestForm ..> reviewRequestPage
reviewListView ..> reviewListPage
reviewEditForm ..> reviewEditPage
projectListView ..> projectListPage
projectEditForm ..> projectEditPage
checkListView ..> checkListPage
checkListEditForm ..> checkListEditPage
menubar ..> consolePage

consoleContents "1" *-- "1" userListPage
consoleContents "1" *-- "1" userEditPage
consoleContents "1" *-- "1" reviewRequestPage
consoleContents "1" *-- "1" reviewListPage
consoleContents "1" *-- "1" reviewEditPage
consoleContents "1" *-- "1" projectListPage
consoleContents "1" *-- "1" projectEditPage
consoleContents "1" *-- "1" checkListPage
consoleContents "1" *-- "1" checkListEditPage

' ##コンテナ - React State 相関関係##
loginFormState ..> loginPage
userListViewState ..> userListPage
userEditFormState ..> userEditPage
reviewRequestFormState ..> reviewRequestPage
reviewListViewState ..> reviewListPage
reviewEditFormState ..> reviewEditPage
projectListViewState ..> projectListPage
projectEditFormState ..> projectEditPage
checkListViewState ..> checkListPage
checkListEditFormState ..> checkListEditPage
menubarState ..> consolePage

' ##レイアウト##
' ## パッケージの位置 ##
views -[hidden]down- state

' ## コンポーネント同士の位置 ##
loginForm -[hidden]right- userListView
userListView -[hidden]right- userEditForm
userEditForm -[hidden]right- reviewRequestForm
reviewRequestForm -[hidden]right- reviewListView
reviewListView -[hidden]right- reviewEditForm
reviewEditForm -[hidden]down- projectListView
projectListView -[hidden]right- projectEditForm
projectEditForm -[hidden]right- checkListView
checkListView -[hidden]right- checkListEditForm
checkListEditForm -[hidden]right- menubar

' ## コンテナ同士の位置
loginPage -[hidden]right- userListPage
userListPage -[hidden]right- userEditPage
userEditPage -[hidden]right- reviewRequestPage
reviewRequestPage -[hidden]right- reviewListPage
reviewListPage -[hidden]right- reviewEditPage
reviewEditPage -[hidden]right- projectListPage
projectListPage -[hidden]right- projectEditPage
projectEditPage -[hidden]right- checkListPage
checkListPage -[hidden]right- checkListEditPage
reviewListPage -[hidden]down- consolePage

' ## コンテナとコンポーネントの位置 ##
loginForm -[hidden]down- loginPage
userListView -[hidden]down- userListPage
userEditForm -[hidden]down- userEditPage
reviewRequestForm -[hidden]down- reviewRequestPage
reviewListView -[hidden]down- reviewListPage
reviewEditForm -[hidden]down- reviewEditPage
projectListView -[hidden]down- projectListPage
projectEditForm -[hidden]down- projectEditPage
checkListView -[hidden]down- checkListPage
checkListEditForm -[hidden]down- checkListEditPage

' ## React State同士の位置 ##
loginFormState -[hidden]right- userListViewState
userListViewState -[hidden]right- userEditFormState
userEditFormState -[hidden]right- reviewRequestFormState
reviewRequestFormState -[hidden]right- reviewListViewState
reviewListViewState -[hidden]right- reviewEditFormState
reviewEditFormState -[hidden]down- projectListViewState
projectListViewState -[hidden]right- projectEditFormState
projectEditFormState -[hidden]right- checkListViewState
checkListViewState -[hidden]right- checkListEditFormState

@enduml
