version: '3.1'

services:

    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGO_INITDB_DATABASE
        ports:
            - 27017
        volumes:
            - mongo_db:/data/db
            #- ./configdb:/data/configdb
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME
            - ME_CONFIG_MONGODB_ADMINPASSWORD
        depends_on:
            - mongo

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:8080
        links:
            - mongo
        depends_on:
            - mongo

volumes:
    mongo_db: