@startuml

[*] --> ログイン画面
ログイン画面: entry/初期表示
ログイン画面: exit/ログアウト

ログイン画面 --> ダッシュボード画面

ダッシュボード画面: entry/一覧表示
ダッシュボード画面: do/各種画面遷移
ダッシュボード画面: exit/ログイン画面に戻る

ダッシュボード画面 --> レビュー依頼作成画面

レビュー依頼作成画面: entry/レビュー依頼フォーム表示
レビュー依頼作成画面: do/レビュー依頼登録
レビュー依頼作成画面: exit/レビュー記録一覧画面に遷移

ダッシュボード画面 --> レビュー記録一覧画面
レビュー記録一覧画面 --> ダッシュボード画面

レビュー記録一覧画面: entry/レビュー記録一覧表示
レビュー記録一覧画面: do/レビュー記録の削除
レビュー記録一覧画面: exit/レビュー記録詳細画面へ遷移

レビュー記録一覧画面 --> レビュー記録詳細画面
レビュー記録詳細画面 --> レビュー記録一覧画面
レビュー依頼作成画面 --> レビュー記録一覧画面
レビュー記録一覧画面 --> レビュー依頼作成画面

レビュー記録詳細画面: entry/レビュー記録表示
レビュー記録詳細画面: do/レビュー記録内容更新
レビュー記録詳細画面: exit/レビュー記録一覧画面へ遷移

ダッシュボード画面 --> プロジェクト管理画面

プロジェクト管理画面: entry/プロジェクト一覧表示
プロジェクト管理画面: do/プロジェクト削除
プロジェクト管理画面: exit/各種画面遷移

プロジェクト管理画面 --> レビュー記録一覧画面: 選択したプロジェクトのレビュー記録のみにフィルタする
プロジェクト管理画面 --> ダッシュボード画面
プロジェクト管理画面 --> プロジェクト編集画面: プロジェクト管理者ロールのユーザーのみ

プロジェクト編集画面: entry/プロジェクト編集フォーム表示
プロジェクト編集画面: do/新規プロジェクト登録・既存プロジェクト情報変更
プロジェクト編集画面: exit/プロジェクト管理画面へ遷移

プロジェクト編集画面 --> プロジェクト管理画面

ダッシュボード画面 --> ユーザー一覧画面

ユーザー一覧画面: entry/ユーザー一覧表示
ユーザー一覧画面: do/ユーザー削除
ユーザー一覧画面: exit/ダッシュボード画面に遷移

ユーザー一覧画面 --> ダッシュボード画面: システム管理者ユーザーのみ
ユーザー一覧画面 --> ユーザー編集画面

ユーザー編集画面: entry/ユーザー情報編集フォーム表示
ユーザー編集画面: do/ユーザー登録・ユーザー情報編集・ユーザー削除
ユーザー編集画面: exit/ユーザー一覧画面へ遷移

ユーザー編集画面 --> ユーザー一覧画面

ダッシュボード画面 --> チェックリスト一覧画面

チェックリスト一覧画面: entry/チェックリスト一覧表示
チェックリスト一覧画面: do/チェックリスト削除
チェックリスト一覧画面: exit/ダッシュボード画面へ遷移

チェックリスト一覧画面 --> ダッシュボード画面
チェックリスト一覧画面 --> チェックリスト編集画面

チェックリスト編集画面: entry/チェックリスト編集フォーム表示
チェックリスト編集画面: do/チェックリスト登録・編集・削除
チェックリスト編集画面: exit/チェックリスト一覧画面へ遷移

チェックリスト編集画面 --> チェックリスト一覧画面
ダッシュボード画面 --> チェックリスト編集画面


' ##レイアウト##
[*] -[hidden]down-> ログイン画面
ログイン画面 -[hidden]down-> ダッシュボード画面
ダッシュボード画面 -[hidden]down-> レビュー記録一覧画面
ダッシュボード画面 -[hidden]down-> レビュー依頼作成画面
ダッシュボード画面 -[hidden]left-> レビュー依頼作成画面
ダッシュボード画面 -[hidden]up-> ユーザー一覧画面
ダッシュボード画面 -[hidden]right-> ユーザー一覧画面
ダッシュボード画面 -[hidden]right-> チェックリスト編集画面

@enduml